### ISSUE TITLE
Bug with quadrature rules for hexahedral element

### ISSUE THREAD

**Issue by npaster** [wareHHOuse/diskpp#41]
This issue is to remind us that there is still a bug with quadrature rules for hexahedral element (don't be surprise if you sting results). For me, the mapping between the reference element end the current element is false (I have to correct it).

**Comment by datafl4sh** [comment]
Thank you for pointing it out @npaster. I think you noticed that I started to work on tests for quadrature rules, this in the near future will allow us to be very sure about what quadratures are actually doing.

**Comment by datafl4sh** [comment]
Solved in #43 by @npaster. Closing the issue.
