### ISSUE TITLE
Installation problem "diffusion_low_grad_vector.dir/depend" -- because of (c)make ?

### ISSUE THREAD

**Issue by ceboy** [wareHHOuse/diskpp#48]
After cmake, I run make and here is the compilation error at 24% :

apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/build.make:62: recipe for target 'apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/diffusion_low_grad_vector.cpp.o' failed
make[2]: *** [apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/diffusion_low_grad_vector.cpp.o] Error 1
CMakeFiles/Makefile2:599: recipe for target 'apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/all' failed
make[1]: *** [apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Here is the instruction that failed (extract from CMakeFiles/Makefile2):
 594 #=============================================================================
 595 # Target rules for target apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir
 596 
 597 # All Build rule for target.
 598 apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/all: CMakeFiles/diskpp.dir/all
 599     $(MAKE) -f apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/build.make apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/depend
 600     $(MAKE) -f apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/build.make apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/build
 601     @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=/home/ceboy/Partage/GIT/diskpp/build/CMakeFiles --progress-num=19,20 "Built target diffusion_low_grad_ve     ctor"
 602 .PHONY : apps/diffusion/CMakeFiles/diffusion_low_grad_vector.dir/all

Any idea about what went wrong ?

**Comment by datafl4sh** [comment]
Thank you @ceboy for filing this issue.

Unfortunately from the log you attached it is not possible to deduce much information useful to solve your problem. Could you  please send the output of just `make diffusion_low_grad_vector`?

I will try to document the DiSk++ build process in the next few days, however a couple of points to check:

- Did you check out the repository with `git clone --recursive`?
- On which system are you compiling the library?

**Comment by ceboy** [comment]
Here is the error at 92% when compiling : make diffusion_low_grad_vector

diskpp/core/revolution/methods/../implementation_bits/methods_hho.hpp:2392:37: error: no match for ‘operator-=’ (operand types are ‘Eigen::internal::enable_if<true, Eigen::IndexedView<Eigen::Matrix<double, -1, 1>, revolution::diffusion_condensed_assembler_vector<disk::mesh<double, 2, disk::mesh_storage<double, 2, disk::generic_storage_class<2> > > >::assembly_index, Eigen::internal::SingleRange> >::type {aka Eigen::IndexedView<Eigen::Matrix<double, -1, 1>, revolution::diffusion_condensed_assembler_vector<disk::mesh<double, 2, disk::mesh_storage<double, 2, disk::generic_storage_class<2> > > >::assembly_index, Eigen::internal::SingleRange>}’ and ‘double’)
                     RHS(asm_map[i]) -= lhs(i,j) * dirichlet_data(j);
In file included from /usr/local/include/eigen3/Eigen/Core:485:0,
                 from /usr/local/include/eigen3/Eigen/SparseCore:11,
                 from /usr/local/include/eigen3/Eigen/PardisoSupport:11,
                 from /home/sboyaval/Partage/GIT/diskpp/core/common/eigen.hpp:34,
                 from /home/sboyaval/Partage/GIT/diskpp/core/mesh/point.hpp:30,
                 from /home/sboyaval/Partage/GIT/diskpp/core/mesh/mesh_storage.hpp:28,
                 from /home/sboyaval/Partage/GIT/diskpp/core/mesh/mesh.hpp:66,
                 from /home/sboyaval/Partage/GIT/diskpp/core/geometry/geometry.hpp:27,
                 from /home/sboyaval/Partage/GIT/diskpp/apps/diffusion/diffusion_low_grad_vector.cpp:11:

I am running 4.15.0-45-generic #48-Ubuntu

**Comment by datafl4sh** [comment]
Hi @ceboy ,

I have the impression that the problems originate from Eigen, and in the past we already experienced similar issues on Ubuntu.

From your log I notice you are currently in the branch `master`, however in `devel` we have some improvements that did not land in `master` yet, in particular for this issue.

What I suggest to you is the following:

- checkout the `devel` branch
- go in the `diskpp/contrib` folder and run `./get_eigen.sh`
- in the build directory, remove CMakeCache.txt and CMakeFiles
- re-run `cmake`
- `make`

The `./get_eigen.sh` script fetches Eigen and puts it directly in the DiSk++ tree. The `CMakeLists.txt` gives priority to the user-provided copy of Eigen.

Let us know.

**Comment by ceboy** [comment]
It worked, thx
