### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by thelfer** [wareHHOuse/diskpp#61]
Could you precise the licence of `DiSk++` ?
I did not find this information in the `README` and there is no `LICENCE` file at the root directory.

Some header files indicates the Mozilla Public License, v. 2.0.

Does this licence apply to the whole project ?

**Comment by datafl4sh** [comment]
Hello @thelfer

DiSk++ is released under MPL, as you correctly spotted in the headers. I added `LICENSE.md` to make things clear.

**Comment by thelfer** [comment]
Thanks @datafl4sh
